name: REST API

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker Network
        run: docker network create data

      - name: Build docker images
        run: docker build -t local .

      - name: Run docker container
        run: docker run -d -p 80:80 --network data local

      - name: Run Newman
        run: docker run --network data postman/newman:latest run /tests/Test_API.postman_collection.json --reporters cli,junit --reporter-junit-export results.xml

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Newman Tests
          path: results.xml
          reporter: java-junit
          fail-on-error: true